create table if not exists public.viewpoints (
  id text primary key,
  mountain_id text not null,
  name text not null,
  subtitle text not null default '',
  elevation text,
  image_key text,
  accent_color text default '#C9A96E',
  distance_from_start text,
  estimated_hike text,
  best_time text,
  description text,
  tags text[] not null default array[]::text[],
  features jsonb not null default '[]'::jsonb,
  trail_notes text[] not null default array[]::text[],
  difficulty text not null default 'Moderate' check (difficulty in ('Easy', 'Moderate', 'Hard', 'Expert')),
  trail_status text not null default 'Open',
  crowd_level text not null default 'Low',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists viewpoints_mountain_id_idx
  on public.viewpoints (mountain_id);

create index if not exists viewpoints_name_idx
  on public.viewpoints (name);

alter table public.viewpoints enable row level security;

drop policy if exists "Public can read viewpoints" on public.viewpoints;
create policy "Public can read viewpoints"
  on public.viewpoints for select to anon, authenticated using (true);

grant select on public.viewpoints to anon;
grant select on public.viewpoints to authenticated;

grant insert, update, delete on public.viewpoints to service_role;

insert into public.viewpoints (
  id, mountain_id, name, subtitle, elevation, image_key, accent_color,
  distance_from_start, estimated_hike, best_time, description, tags,
  features, trail_notes, difficulty, trail_status, crowd_level
)
values
  ('v1', '1', 'Barangay Flores Trailhead', 'Mt. Madja-as Start', '~550m', 'trailhead', '#FF6B6B', '0 km', '0 hrs', 'Early morning 5-6 AM', 'The primary jump-off point for Mt. Madja-as located in Barangay Flores, Culasi, Antique. This is where hikers register and obtain permits. The trailhead is well-marked with facilities nearby including a small store for last-minute supplies. The trail starts relatively easy before steepening significantly.', ARRAY['Trailhead','Permits Required','Water Available','Guides Available']::text[], '[{"icon":"water-outline","text":"Water source nearby","safe":true},{"icon":"people-outline","text":"Local guides available","safe":true},{"icon":"document-outline","text":"Permit station","safe":true},{"icon":"warning-outline","text":"Steep ascent begins here","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Low'),
  ('v2', '1', 'First Water Source', 'Early Trail Marker', '~750m', 'waterfall', '#4ECDC4', '2.5 km', '1.5 hrs', 'Mid-morning', 'A reliable water source encountered early in the trek. This is an excellent spot to refill water bottles and rest before the steep ascent section begins. The area is relatively shaded with occasional views of the surrounding valleys.', ARRAY['Water Source','Refill Point','Good Views','Rest Area']::text[], '[{"icon":"water-outline","text":"Fresh water spring","safe":true},{"icon":"leaf-outline","text":"Shaded forest area","safe":true},{"icon":"sunny-outline","text":"Partial forest coverage","safe":true},{"icon":"alert-circle-outline","text":"Steep terrain ahead","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Low'),
  ('v3', '1', 'Camp 1 - Mamay Camp', 'First Night Camp', '~1,100m', 'camp1', '#95E1D3', '5 km', '3-4 hrs', 'Late afternoon arrival', 'The most popular first camp for Mt. Madja-as climbers. Mamay Camp is a well-established camping area with space for multiple tents and basic facilities. The camp has water access and offers beautiful views of the valleys below. Many hikers prefer stopping here for the night before the final push to summit.', ARRAY['Camping Site','Multiple Tents','Water Available','Popular Camp']::text[], '[{"icon":"home-outline","text":"Multiple camping spots","safe":true},{"icon":"water-outline","text":"Water available nearby","safe":true},{"icon":"sunny-outline","text":"Beautiful sunset views","safe":true},{"icon":"moon-outline","text":"Clear night sky","safe":true}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Low'),
  ('v4', '1', 'Ridge Trail Section', 'Grassland Ridge', '~1,200m', 'crown_shyness', '#F38181', '7 km', '4-5 hrs', 'Early morning hike', 'This section features an open grassland ridge with panoramic views of the surrounding mountains and valleys. The trail becomes more exposed here with minimal shade. The elevation change is moderate but the lack of tree cover makes it feel more challenging. Excellent photography opportunities.', ARRAY['Open Ridge','Exposed Trail','Great Views','Photography']::text[], '[{"icon":"sunny-outline","text":"No shade - sun exposure","safe":false},{"icon":"eye-outline","text":"360° panoramic views","safe":true},{"icon":"camera-outline","text":"Photo-worthy landscape","safe":true},{"icon":"alert-circle-outline","text":"Afternoon storms possible","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Medium'),
  ('v5', '1', 'Lake Viewpoint', 'Scenic Lake Views', '~1,300m', 'waterfall', '#87CEEB', '10 km (descent route)', '6-7 hrs from summit', 'Afternoon descent', 'An exceptional viewpoint on the descent route offering views of alpine lakes and valleys. This area provides a different perspective from the main route and is popular with photographers. The descent trail is slightly easier here with better defined paths.', ARRAY['Lake Views','Descent Route','Photography','Alpine Lakes']::text[], '[{"icon":"water-outline","text":"Alpine lake views","safe":true},{"icon":"eye-outline","text":"Excellent photo spots","safe":true},{"icon":"sunny-outline","text":"Better light during descent","safe":true},{"icon":"alert-circle-outline","text":"Loose terrain on descent","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Low'),
  ('v6', '1', 'Camp 2 - Upper Camp', 'High Altitude Camp', '~1,280m', 'camp2', '#AA96DA', '8.5 km', '5-6 hrs', 'Late afternoon', 'A secondary camping area situated closer to the summit, offering a more direct approach for an early morning summit attempt. Camp 2 is smaller and more exposed than Mamay Camp but provides better starting point for sunrise at the peak. Water must be collected from higher elevations.', ARRAY['Upper Camp','Summit Staging','Minimal Shade','Alpine']::text[], '[{"icon":"arrow-up-outline","text":"High altitude zone","safe":false},{"icon":"home-outline","text":"Limited camping spots","safe":true},{"icon":"moon-outline","text":"Stunning night sky","safe":true},{"icon":"water-outline","text":"Water collection challenging","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Low'),
  ('v7', '1', 'Hidden Spring', 'Water on Descent', '~1,290m', 'waterfall', '#20B2AA', '9.5 km (descent)', '5-6 hrs from summit', 'Mid-descent hydration stop', 'A precious fresh water source found on the descent route. This hidden spring is critical for refilling water bottles on the return journey. The spring is reliable and flows year-round, making it an essential refill point before the final descent to basecamp.', ARRAY['Water Source','Descent Route','Refill Point','Fresh Spring']::text[], '[{"icon":"water-outline","text":"Fresh spring water","safe":true},{"icon":"leaf-outline","text":"Shaded from forest","safe":true},{"icon":"alert-circle-outline","text":"Can be slow flowing in dry season","safe":false},{"icon":"home-outline","text":"Rest area on descent","safe":true}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Low'),
  ('v8', '1', 'Grassy Meadow', 'Alpine Meadow', '~1,250m', 'mossy_forest', '#90EE90', '8.5 km (descent)', '4-5 hrs from summit', 'Afternoon descent', 'A scenic grassy meadow filled with alpine wildflowers in season. This area provides a comfortable rest point with good views and photo opportunities. The relatively flat terrain is a welcome relief on tired legs during the descent. Excellent for wildlife spotting.', ARRAY['Meadow','Wildflowers','Rest Area','Wildlife']::text[], '[{"icon":"flower-outline","text":"Wildflowers in season","safe":true},{"icon":"eye-outline","text":"Wildlife viewing area","safe":true},{"icon":"camera-outline","text":"Scenic landscape photos","safe":true},{"icon":"sunny-outline","text":"Open area - sun exposure","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Low'),
  ('v9', '1', 'Mt. Madja-as Summit', 'Highest Peak in Antique', '~1,338m', 'summit', '#FFD700', '11 km', '7-8 hrs', 'Sunrise at peak', 'The summit of Mt. Madja-as offers a 360-degree panoramic view encompassing Panay Island, views toward Negros, and the Sibuyan Sea on clear days. There is a peak marker and often a register book for hikers to sign. The summit experience is truly rewarding after the challenging climb.', ARRAY['Summit Peak','Panoramic Views','Peak Marker','Monument']::text[], '[{"icon":"flag-outline","text":"Official peak marker","safe":true},{"icon":"eye-outline","text":"360° island views","safe":true},{"icon":"camera-outline","text":"Prime photo location","safe":true},{"icon":"alert-circle-outline","text":"Exposed to weather","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Medium'),
  ('v10', '1', 'Summit Ridge', 'Final Approach', '~1,310m', 'summit_ridge', '#FCBAD3', '10 km', '6-7 hrs', 'Pre-dawn for sunrise', 'The final approach to Mt. Madja-as summit features steep rocky terrain. This section is the most challenging part of the hike with loose rocks and steep inclines. The trail is well-defined but requires careful footing. Reaching the ridge early allows for sunrise views from the summit.', ARRAY['Rocky Terrain','Steep','Final Push','Exposed']::text[], '[{"icon":"alert-circle-outline","text":"Loose rock hazard","safe":false},{"icon":"trending-up-outline","text":"Very steep incline","safe":false},{"icon":"eye-outline","text":"Sunrise views possible","safe":true},{"icon":"cloudy-outline","text":"Strong winds at ridge","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Medium'),
  ('v11', '2', 'Bontoc Trailhead', 'Technical Route Start', '~500m', 'trailhead', '#E74C3C', '0 km', '0 hrs', 'Early morning', 'The starting point for the technically challenging Mt. Guiting-Guiting route from Bontoc. This expert-only mountain requires mandatory guides and prior climbing experience. The trailhead is less developed than other mountains, reflecting the technical nature of this climb.', ARRAY['Expert Route','Guides Required','Technical','Rock Climbing']::text[], '[{"icon":"warning-outline","text":"Expert climbers only","safe":false},{"icon":"people-outline","text":"Guides mandatory","safe":true},{"icon":"alert-circle-outline","text":"Technical rock scrambling","safe":false},{"icon":"shield-checkmark-outline","text":"Safety equipment needed","safe":false}]'::jsonb, ARRAY[]::text[], 'Expert', 'Open', 'Low'),
  ('v12', '2', 'Lower Ridge Camp', 'First Technical Camp', '~1,200m', 'camp1', '#C0392B', '6 km', '4-5 hrs', 'Late afternoon', 'The initial camp where hikers acclimatize to the technical terrain ahead. This camp sits at the base of the main ridge system. Equipment check and strategy discussion happens here before the challenging knife-edge ridge traverse.', ARRAY['Technical Camp','Ridge Base','Equipment Check','Guides Present']::text[], '[{"icon":"alert-circle-outline","text":"Exposed campsite","safe":false},{"icon":"water-outline","text":"Water collection nearby","safe":true},{"icon":"trending-up-outline","text":"Sharp elevation gain ahead","safe":false},{"icon":"home-outline","text":"Limited camping spots","safe":true}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Low'),
  ('v13', '2', 'Kiss The Wall', 'Famous Rock Feature', '~1,850m', 'summit_ridge', '#E67E22', '10 km', '6-7 hrs', 'Daytime only', 'The most famous feature on Mt. Guiting-Guiting - a distinctive rock formation that requires climbers to hug the rock face closely. This iconic landmark is both a technical challenge and a major accomplishment for those who reach it. The name comes from the necessity of pressing against the rock to pass safely.', ARRAY['Famous Feature','Technical Climb','Rock Scramble','Icon']::text[], '[{"icon":"alert-circle-outline","text":"Dangerous rock scramble","safe":false},{"icon":"camera-outline","text":"Photo opportunity at feature","safe":true},{"icon":"trending-up-outline","text":"Extreme exposure","safe":false},{"icon":"cloudy-outline","text":"Strong winds at wall","safe":false}]'::jsonb, ARRAY[]::text[], 'Expert', 'Open', 'Low'),
  ('v14', '2', 'Mt. Guiting-Guiting Summit', 'Expert Peak', '~2,058m', 'summit', '#D35400', '12 km', '8-9 hrs', 'Early morning', 'The summit of Mt. Guiting-Guiting requires technical rock climbing skills and is one of the most challenging peaks in the Philippines. The rewards include stunning views and the satisfaction of conquering one of Asia''s most technical mountains. Ropes and climbing gear are essential.', ARRAY['Technical Summit','Rope Required','Expert Only','Extreme']::text[], '[{"icon":"alert-circle-outline","text":"Rope climbing required","safe":false},{"icon":"eye-outline","text":"Panoramic peak views","safe":true},{"icon":"flag-outline","text":"Summit marker","safe":true},{"icon":"trending-up-outline","text":"Extreme altitude exposure","safe":false}]'::jsonb, ARRAY[]::text[], 'Expert', 'Open', 'Low'),
  ('v15', '3', 'Ambangeg Trailhead', 'Main Pulag Route', '~1,500m', 'trailhead', '#3498DB', '0 km', '0 hrs', 'Early morning 4 AM', 'The primary and most popular starting point for Mt. Pulag. Located in Nueva Vizcaya, this trailhead has ranger facilities and permit stations. The area is well-maintained with good infrastructure. Most hikers start here for their sea of clouds adventure.', ARRAY['Main Route','Ranger Station','Permits Required','Infrastructure']::text[], '[{"icon":"document-outline","text":"Permit station available","safe":true},{"icon":"people-outline","text":"Ranger presence","safe":true},{"icon":"water-outline","text":"Water facilities","safe":true},{"icon":"trending-up-outline","text":"Immediate steep ascent","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Medium'),
  ('v16', '3', 'First Campsite', 'Lower Camp', '~1,800m', 'camp1', '#2980B9', '5 km', '2-3 hrs', 'Afternoon arrival', 'The first major camping area on the Ambangeg trail. This established camp has basic facilities and is popular with day-hikers attempting the sea of clouds. The elevation is rising significantly, and altitude effects may begin here.', ARRAY['First Camp','Sea of Clouds Base','Multiple Sites','Altitude Zone']::text[], '[{"icon":"home-outline","text":"Multiple camping spots","safe":true},{"icon":"water-outline","text":"Water sources nearby","safe":true},{"icon":"warning-outline","text":"Altitude effects begin","safe":false},{"icon":"sunny-outline","text":"Minimize sun exposure","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Medium'),
  ('v17', '3', 'Eddet Camp', 'Sea of Clouds Camp', '~2,600m', 'camp2', '#1ABC9C', '11 km', '6-7 hrs', 'Late afternoon for sunrise', 'Famous camp known for its phenomenal sea of clouds views. Climbers camp here to experience the magical sunrise above the clouds. This is the highest camp and is particularly cold at night. Water is scarce and must be collected carefully.', ARRAY['Sea of Clouds','Sunrise Views','Famous Camp','High Altitude']::text[], '[{"icon":"eye-outline","text":"Famous sea of clouds view","safe":true},{"icon":"camera-outline","text":"Sunrise photo opportunity","safe":true},{"icon":"thermometer-outline","text":"Extremely cold at night","safe":false},{"icon":"water-outline","text":"Water collection difficult","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Low'),
  ('v18', '3', 'Mt. Pulag Summit', 'Sea of Clouds Peak', '~2,926m', 'summit', '#16A085', '13 km', '7-8 hrs', 'Sunrise attempt', 'Philippines'' third highest mountain featuring the legendary "sea of clouds" phenomenon. The summit offers 360-degree views and on clear days, visibility extends across multiple provinces. The sunrise experience is considered one of the best in the country.', ARRAY['Highest Peak','Sea of Clouds','Sunrise Views','Monument']::text[], '[{"icon":"eye-outline","text":"Unparalleled cloud views","safe":true},{"icon":"sunny-outline","text":"Spectacular sunrise","safe":true},{"icon":"flag-outline","text":"Historic peak marker","safe":true},{"icon":"warning-outline","text":"Extreme wind exposure","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Low'),
  ('v19', '4', 'Kapatagan Trailhead', 'Highest Mountain Start', '~600m', 'trailhead', '#8E44AD', '0 km', '0 hrs', 'Very early morning', 'The primary jump-off point for Mt. Apo, the Philippines'' highest mountain. Located in Davao, this trailhead requires government permits and is well-developed with ranger facilities. The climb to the summit will take 2-3 days minimum.', ARRAY['Highest Mountain','Government Permits','Ranger Presence','Long Trek']::text[], '[{"icon":"document-outline","text":"Government permits mandatory","safe":true},{"icon":"people-outline","text":"Rangers on duty","safe":true},{"icon":"warning-outline","text":"Extremely long hike ahead","safe":false},{"icon":"shield-checkmark-outline","text":"Mandatory guide system","safe":true}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Low'),
  ('v20', '4', 'Lake Venado Camp', 'Alpine Lake Zone', '~1,500m', 'camp1', '#8E44AD', '8 km', '5-6 hrs', 'Afternoon arrival', 'A beautiful alpine lake surrounded by primary forest. This camp offers respite in a biodiversity hotspot. The lake provides reliable water and the area is known for unique wildlife. Many hikers rest here before the final push.', ARRAY['Alpine Lake','Forest Camp','Wildlife Zone','Water Source']::text[], '[{"icon":"water-outline","text":"Alpine lake water","safe":true},{"icon":"leaf-outline","text":"Rich forest ecosystem","safe":true},{"icon":"eye-outline","text":"Wildlife viewing","safe":true},{"icon":"alert-circle-outline","text":"Can be misty and cold","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Low'),
  ('v21', '4', 'Mt. Apo Summit', 'Highest Peak in Philippines', '~2,954m', 'summit', '#9B59B6', '18 km', '12-15 hrs (over 2-3 days)', 'Clear dry season', 'The summit of Mt. Apo is the highest point in the Philippines. The peak features an active volcanic crater and stunning views of Mindanao and surrounding islands. Standing at the highest point in the country is an unforgettable achievement.', ARRAY['Highest Peak','Active Volcano','Crater View','Monument']::text[], '[{"icon":"flag-outline","text":"Highest peak in PH","safe":true},{"icon":"warning-outline","text":"Active volcanic area","safe":false},{"icon":"eye-outline","text":"360° panoramic views","safe":true},{"icon":"thermometer-outline","text":"Extreme altitude exposure","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Low'),
  ('v22', '5', 'Cagsawa Trailhead', 'Perfect Cone Start', '~500m', 'trailhead', '#E74C3C', '0 km', '0 hrs', 'Pre-dawn start', 'The main starting point for Mt. Mayon, the world''s most perfectly cone-shaped volcano. Located in Albay, this trailhead is easily accessible and well-maintained. The hike is challenging but achievable for experienced hikers.', ARRAY['Perfect Cone','Volcano','Accessible','Popular Route']::text[], '[{"icon":"document-outline","text":"Permits required","safe":true},{"icon":"people-outline","text":"Guides available","safe":true},{"icon":"warning-outline","text":"Active volcano precautions","safe":false},{"icon":"trending-up-outline","text":"Very steep initial ascent","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Medium'),
  ('v23', '5', 'Base Camp', 'First Camp', '~1,200m', 'camp1', '#C0392B', '6 km', '3-4 hrs', 'Late afternoon', 'The first major camp on the ascent of Mt. Mayon. Located on the cone slope with good water access. Camp infrastructure is basic but adequate. The cone shape becomes more apparent from this elevation.', ARRAY['First Camp','Cone View','Water Available','Rest Point']::text[], '[{"icon":"water-outline","text":"Water sources available","safe":true},{"icon":"home-outline","text":"Established campsite","safe":true},{"icon":"eye-outline","text":"Cone slope views","safe":true},{"icon":"alert-circle-outline","text":"Volcanic ash terrain","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Medium'),
  ('v24', '5', 'Crater Rim', 'Summit Approach', '~2,300m', 'summit_ridge', '#E67E22', '10 km', '6-7 hrs', 'Early morning', 'The final approach to Mt. Mayon''s summit is extremely steep with loose volcanic ash. This section tests endurance as hikers often slide backward with each step. The effort is rewarded with views of the perfectly formed crater.', ARRAY['Crater Approach','Steep Ash','Final Push','Volcanic']::text[], '[{"icon":"alert-circle-outline","text":"Volcanic ash terrain slippery","safe":false},{"icon":"trending-up-outline","text":"Extreme steepness","safe":false},{"icon":"eye-outline","text":"Crater views ahead","safe":true},{"icon":"warning-outline","text":"Loose scree hazard","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Low'),
  ('v25', '5', 'Mt. Mayon Summit', 'Perfect Cone Peak', '~2,463m', 'summit', '#D35400', '11 km', '7-8 hrs', 'Sunrise attempt', 'Standing at the summit of Mt. Mayon offers views of its perfectly symmetrical cone and expansive vistas of Albay and the Bicol region. The active volcanic crater is visible from the summit. This is one of the most photographed peaks in the Philippines.', ARRAY['Perfect Cone','Active Crater','Popular Peak','Photo Spot']::text[], '[{"icon":"eye-outline","text":"Perfect cone views","safe":true},{"icon":"camera-outline","text":"Iconic photo location","safe":true},{"icon":"flag-outline","text":"Summit marker","safe":true},{"icon":"warning-outline","text":"Active volcanic area","safe":false}]'::jsonb, ARRAY[]::text[], 'Hard', 'Open', 'Low'),
  ('v26', '6', 'Old Trail Junction', 'Beginner Route Start', '~300m', 'trailhead', '#27AE60', '0 km', '0 hrs', 'Early morning', 'The starting point for the easier route of Mt. Batulao. This beginner-friendly trail is perfect for first-time hikers. The trailhead is accessible and well-marked. The hike takes 2-3 hours round trip.', ARRAY['Beginner Route','Easy Hike','Day Trip','Accessible']::text[], '[{"icon":"leaf-outline","text":"Easy forest trail","safe":true},{"icon":"sunny-outline","text":"Good shade coverage","safe":true},{"icon":"people-outline","text":"Beginner-friendly","safe":true},{"icon":"trending-up-outline","text":"Gradual elevation gain","safe":true}]'::jsonb, ARRAY[]::text[], 'Easy', 'Open', 'High'),
  ('v27', '6', 'Mt. Batulao Summit', 'Twin Peaks', '~811m', 'summit', '#16A085', '5 km', '2-3 hrs', 'Daytime', 'Mt. Batulao actually has two summits connected by a ridge. Both offer good views of Batangas province. This is an ideal introductory mountain with manageable distances and moderate difficulty. Excellent for building hiking experience.', ARRAY['Twin Summits','Easy Day Hike','Views','Batangas']::text[], '[{"icon":"flag-outline","text":"Twin peak markers","safe":true},{"icon":"eye-outline","text":"Good valley views","safe":true},{"icon":"camera-outline","text":"Scenic photo spots","safe":true},{"icon":"people-outline","text":"Crowded weekends","safe":true}]'::jsonb, ARRAY[]::text[], 'Easy', 'Open', 'High'),
  ('v28', '7', 'Sto. Tomas Trailhead', 'Grotto Route Start', '~200m', 'trailhead', '#2980B9', '0 km', '0 hrs', 'Early morning', 'The main trailhead for Mt. Maculot located near Sto. Tomas. This is one of the closest mountains to Metro Manila, making it a favorite weekend hike. The route passes by a famous grotto shrine.', ARRAY['Near Manila','Easy Access','Popular','Grotto Route']::text[], '[{"icon":"car-outline","text":"Easy vehicle access","safe":true},{"icon":"people-outline","text":"Well-maintained trail","safe":true},{"icon":"sunny-outline","text":"Some shade available","safe":true},{"icon":"warning-outline","text":"Crowded on weekends","safe":true}]'::jsonb, ARRAY[]::text[], 'Easy', 'Open', 'High'),
  ('v29', '7', 'Grotto Shrine', 'Religious Site', '~400m', 'camp1', '#8E44AD', '1.5 km', '0.5 hrs', 'Morning', 'A beautiful grotto shrine dedicated to the Virgin Mary, located about 30 minutes from the trailhead. This is a pilgrimage site and a spiritual point of interest for many hikers. The area is peaceful with good water access.', ARRAY['Religious Site','Grotto','Pilgrimage','Rest Point']::text[], '[{"icon":"water-outline","text":"Fresh water available","safe":true},{"icon":"people-outline","text":"Pilgrimage site","safe":true},{"icon":"leaf-outline","text":"Shaded grotto area","safe":true},{"icon":"trending-up-outline","text":"Trail steepens above","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Medium'),
  ('v30', '7', 'The Rockies', 'Rock Formation Feature', '~920m', 'summit_ridge', '#E67E22', '4 km', '2-2.5 hrs', 'Late morning', 'Famous rock formations at Mt. Maculot providing spectacular views of Taal Lake and Taal Volcano. The Rockies are the highlight of the hike featuring dramatic boulders and a cable bridge crossing. Excellent photography location.', ARRAY['Rock Formation','Taal Lake View','Cable Bridge','Photo Spot']::text[], '[{"icon":"camera-outline","text":"Excellent photo opportunity","safe":true},{"icon":"eye-outline","text":"Taal Lake & Volcano views","safe":true},{"icon":"alert-circle-outline","text":"Cable bridge adventure","safe":false},{"icon":"sunny-outline","text":"Exposed to sun","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Medium'),
  ('v31', '7', 'Mt. Maculot Summit', 'Taal Lake Peak', '~930m', 'summit', '#1ABC9C', '5 km', '2.5-3 hrs', 'Late morning', 'The summit of Mt. Maculot sits just above the Rockies. From here, views of Taal Lake, Taal Volcano, and Tagaytay are spectacular. This is an ideal day hike for Manila residents with manageable distance and excellent rewards.', ARRAY['Day Hike','Taal View','Easy Summit','Popular Weekend']::text[], '[{"icon":"eye-outline","text":"Taal Lake panorama","safe":true},{"icon":"sunny-outline","text":"Good sunset spot","safe":true},{"icon":"people-outline","text":"Usually crowded","safe":true},{"icon":"camera-outline","text":"Scenic monument location","safe":true}]'::jsonb, ARRAY[]::text[], 'Easy', 'Open', 'High'),
  ('v32', '8', 'Dakak Trailhead', 'Mountain Tourism', '~1,200m', 'trailhead', '#16A085', '0 km', '0 hrs', 'Early morning', 'The starting point for Mt. Ulap located in the Cordillera mountain range. The trailhead is part of a mountain tourism development with facilities and guides. The hike features grassland ridges and pine forests.', ARRAY['Mountain Tourism','Guides Available','Facilities','Cordillera']::text[], '[{"icon":"people-outline","text":"Guides available","safe":true},{"icon":"water-outline","text":"Water facilities","safe":true},{"icon":"home-outline","text":"Basic accommodation","safe":true},{"icon":"trending-up-outline","text":"Steep initial climb","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Medium'),
  ('v33', '8', 'Gungal Rock', 'Famous Boulder', '~1,850m', 'summit_ridge', '#D35400', '7 km', '3-4 hrs', 'Late morning', 'One of the most famous landmarks on Mt. Ulap - a massive boulder formation standing alone on the grassland ridge. Gungal Rock offers spectacular views and is a popular photo spot. The rock can be climbed for even better vantage points.', ARRAY['Boulder Formation','Famous Landmark','Grassland','Photo Spot']::text[], '[{"icon":"camera-outline","text":"Iconic photo location","safe":true},{"icon":"eye-outline","text":"360° grassland views","safe":true},{"icon":"warning-outline","text":"Rock climb required","safe":false},{"icon":"sunny-outline","text":"No shade - sun exposure","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Low'),
  ('v34', '8', 'Mt. Ulap Summit', 'Twin Summits', '~1,850m', 'summit', '#16A085', '8 km', '4-5 hrs', 'Daytime', 'Mt. Ulap features twin summits connected by a scenic ridge. The grassland coverage provides unobstructed views of surrounding peaks in the Cordillera. This hike is moderate in difficulty with stunning alpine meadow scenery.', ARRAY['Twin Summits','Alpine Meadow','Scenic Ridge','Cordillera']::text[], '[{"icon":"flag-outline","text":"Twin summit markers","safe":true},{"icon":"eye-outline","text":"Panoramic Cordillera views","safe":true},{"icon":"camera-outline","text":"Great sunrise and sunset photos","safe":true},{"icon":"sunny-outline","text":"Open ridge - sun exposure","safe":false}]'::jsonb, ARRAY[]::text[], 'Moderate', 'Open', 'Medium');
