create table if not exists public.wildtrack_species (
  id bigint primary key,
  scientific_name text not null,
  common_name text not null,
  category text not null,
  conservation_status text,
  gbif_id bigint,
  inaturalist_id bigint,
  image_url text,
  description text,
  habitat text,
  fun_facts text,
  created_at timestamptz not null default now()
);

create table if not exists public.wildtrack_mountain_species (
  id bigint generated by default as identity primary key,
  mountain_id text not null,
  species_id bigint not null references public.wildtrack_species(id) on delete cascade,
  is_endemic boolean not null default false,
  created_at timestamptz not null default now(),
  unique (mountain_id, species_id)
);

create table if not exists public.wildtrack_mountain_biodiversity (
  id text primary key,
  name text not null,
  curated_species_count integer not null default 0,
  description text,
  endemic_species_count integer not null default 0,
  key_species jsonb not null default '[]'::jsonb,
  ecosystem text,
  conservation_status text
);

create table if not exists public.wildtrack_discoveries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  species_id bigint not null references public.wildtrack_species(id) on delete cascade,
  mountain_id text not null,
  discovered_at timestamptz not null default now(),
  latitude double precision,
  longitude double precision,
  notes text,
  unique (user_id, species_id, mountain_id)
);

create index if not exists wildtrack_mountain_species_mountain_idx
  on public.wildtrack_mountain_species (mountain_id);

create index if not exists wildtrack_discoveries_user_mountain_idx
  on public.wildtrack_discoveries (user_id, mountain_id, discovered_at desc);

alter table public.wildtrack_species enable row level security;
alter table public.wildtrack_mountain_species enable row level security;
alter table public.wildtrack_mountain_biodiversity enable row level security;
alter table public.wildtrack_discoveries enable row level security;

drop policy if exists "Authenticated users can read WildTrack species" on public.wildtrack_species;
create policy "Authenticated users can read WildTrack species"
  on public.wildtrack_species for select to authenticated using (true);

drop policy if exists "Authenticated users can read WildTrack mountain species" on public.wildtrack_mountain_species;
create policy "Authenticated users can read WildTrack mountain species"
  on public.wildtrack_mountain_species for select to authenticated using (true);

drop policy if exists "Authenticated users can read WildTrack biodiversity" on public.wildtrack_mountain_biodiversity;
create policy "Authenticated users can read WildTrack biodiversity"
  on public.wildtrack_mountain_biodiversity for select to authenticated using (true);

drop policy if exists "Users can read their WildTrack discoveries" on public.wildtrack_discoveries;
create policy "Users can read their WildTrack discoveries"
  on public.wildtrack_discoveries for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can create their WildTrack discoveries" on public.wildtrack_discoveries;
create policy "Users can create their WildTrack discoveries"
  on public.wildtrack_discoveries for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can delete their WildTrack discoveries" on public.wildtrack_discoveries;
create policy "Users can delete their WildTrack discoveries"
  on public.wildtrack_discoveries for delete to authenticated using (auth.uid() = user_id);
